services:
  - type: web
    name: sentiment-api
    env: python
    plan: free
    buildCommand: pip install -r requirements.txt
    startCommand: bash start.sh
    rootDir: V2.0/sentiment_api
    autoDeploy: true
